name: CI/CD to Aliyun

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. 拉取代码（修正缩进）
      - name: Checkout code
        uses: actions/checkout@v4  # ✅ 正确缩进：与 name 对齐

      # 2. 安装依赖并构建
      - name: Install and Build
        run: |
          npm install
          npm run build

      # 3. 通过 SCP 传输文件
      - name: Upload files via SCP
        uses: appleboy/scp-action@v0.1.0
        with:
          host: ${{ secrets.IP }}
          username: ${{ secrets.ALIYUN_SSH_USER }}
          key: ${{ secrets.ALIYUN_SSH_PRIVATE_KEY }}
          source: "dist/"
          target: "/var/www/myapp"

      # 4. 通过 SSH 部署
      - name: Deploy to Aliyun
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.IP }}
          username: ${{ secrets.ALIYUN_SSH_USER }}
          key: ${{ secrets.ALIYUN_SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/myapp
            git pull origin main
            rm -rf ./dist
            sudo systemctl restart myapp
